Gapura/Controllers/ProductsController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Gapura.BLL.Models;
using Gapura.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gapura.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private YSIDGAEntitiesConn _dbConn = new YSIDGAEntitiesConn();

        //
        // GET: /Products/

        public ActionResult Index()
        {
            var products = _dbConn.Products.Include(p => p.Category).Include(p => p.Supplier);
            return View(products.ToList());
        }

        ///////////////-------------- Load Data by JQuery Fir 26102016 -----------------/////////////
        public ActionResult LoadData()
        {
            //using (YSIDGAEntitiesConn dc = new YSIDGAEntitiesConn())
            {
                _dbConn.Configuration.LazyLoadingEnabled = false;   // if your table is relational, contain foreign key
                #region Various Ways
                //var data = dbConn.Products.OrderBy(p => p.ProductName).ToList();      //default way
                //var data = from p in dbConn.Products
                //           join ca in dbConn.Categories on p.CategoryID equals ca.CategoryID
                //           join s in dbConn.Suppliers on p.SupplierID equals s.SupplierID
                //           orderby p.ProductName
                //           select new { p.ProductID, p.ProductCode, ca.CategoryName, p.ProductName, 
                //                        s.CompanyName, p.QuantityPerUnit, p.UnitPrice, 
                //                        p.ReorderLevel, p.Discontinued, p.Specs };
                ////List<Product> list_product = dbConn.ToList<Product>();                // need if want convert to list
                #endregion

                var Products = _dbConn.SPI_Products().ToList();
                return Json(new { data = Products }, JsonRequestBehavior.AllowGet);
            }
        }
        ///////////////-----------End Load Data by JQuery Fir 26102016 -----------------/////////////

        public JsonResult Upload(Product product)
        {

            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase file = Request.Files[i]; //Uploaded file
                //Use the following properties to get file's name, size and MIMEType
                int fileSize = file.ContentLength;
                string fileName = file.FileName;
                string mimeType = file.ContentType;
                System.IO.Stream fileContent = file.InputStream;

                foreach (string filePhoto in Request.Files)
                {
                    //To save file, use SaveAs method
                    file.SaveAs(Server.MapPath("~/UploadFiles/Item/") + fileName); //File will be saved in exp. root "~/"

                    var postedFile = Request.Files[filePhoto];
                    //postedFile.SaveAs(Server.MapPath("~/img/Photo/") + Path.GetFileName(postedFile.FileName));
                    product.PhotoPath = "~/UploadFiles/Item/" + Path.GetFileName(postedFile.FileName);
                }

                ////To save file, use SaveAs method
                //file.SaveAs(Server.MapPath("~/img/Photo/") + fileName); //File will be saved in exp. root "~/"
            }
            return Json("Uploaded " + Request.Files.Count + " files");
        }

        public JsonResult getProducts()
        {
            //dbConn.Configuration.LazyLoadingEnabled = false;
            List<Product> Products = new List<Product>();
            using (YSIDGAEntitiesConn ItemConn = new YSIDGAEntitiesConn())
            {
                ItemConn.Configuration.LazyLoadingEnabled = false;
                //Products = ItemConn.Products.SqlQuery("SELECT ProductID, ProductName FROM Products").ToList();
                Products = ItemConn.Products.OrderBy(p => p.ProductName).ToList();
                
            }
            //var Products = dbConn.SPR_Products().ToList();
            return new JsonResult { Data = Products, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public JsonResult getProduct(string term)
        {
            var routeList = _dbConn.Products.Where(r => r.ProductName.Contains(term))
                    .Take(6)
                    .Select(r => new { value = r.ProductID, label = r.ProductName });
            return Json(routeList, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Products/Details/5

        public ActionResult Details(int id = 0)
        {
            Product product = _dbConn.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /Products/Create

        public ActionResult Create()
        {
            ViewData["FirstInputDate"] = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
            ViewBag.UnitID = new SelectList(_dbConn.MasterUnits, "UnitID", "UnitName");
            ViewBag.CategoryID = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
            ViewBag.SupplierID = new SelectList(_dbConn.Suppliers, "SupplierID", "CompanyName");

            return View();
        }

        //
        // POST: /Products/Create

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (Request.Files.Count > 0)
            {
                //HttpPostedFileBase file = Request.Files[0];
                foreach (string file in Request.Files)
                {
                    var postedFile = Request.Files[file];
                    //postedFile.SaveAs(Server.MapPath("~/img/Photo/") + Path.GetFileName(postedFile.FileName));
                    product.PhotoPath = "~/UploadFiles/Item/" + Path.GetFileName(postedFile.FileName);
                }
            }
            else
            {
                ViewBag.Message = "Please select the file !";
            }

            if (ModelState.IsValid)
            {
                _dbConn.Products.Add(product);
                _dbConn.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UnitID = new SelectList(_dbConn.MasterUnits, "UnitID", "UnitName", product.UnitID);
            ViewBag.CategoryID = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.SupplierID = new SelectList(_dbConn.Suppliers, "SupplierID", "CompanyName", product.SupplierID);

            return View(product);
        }

        //
        // GET: /Products/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product product = _dbConn.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ViewData["ProductName"] = product.ProductName;
            ViewBag.UnitID = new SelectList(_dbConn.MasterUnits, "UnitID", "UnitName", product.UnitID);
            ViewBag.CategoryID = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.SupplierID = new SelectList(_dbConn.Suppliers, "SupplierID", "CompanyName", product.SupplierID);
            ViewData["FirstInputDate"] = product.FirstInputDate.ToString();

            return View(product);
        }

        //
        // POST: /Products/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    string oldPhotoPath = product.PhotoPath;
                    HttpPostedFileBase file = Request.Files[0];
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        string path = Path.Combine(Server.MapPath("~/UploadFiles/Item/"), fileName);
                        file.SaveAs(path);

                        product.PhotoPath = "/UploadFiles/Item/" + file.FileName;
                        string fullPath = Request.MapPath("~" + oldPhotoPath);
                        if (System.IO.File.Exists(fullPath))
                        {
                            System.IO.File.Delete(fullPath);
                        }
                    }
                    else
                    {
                        ViewData["PhotoPath"] = product.PhotoPath;
                    }
                }

                _dbConn.Entry(product).State = EntityState.Modified;
                _dbConn.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UnitID = new SelectList(_dbConn.MasterUnits, "UnitID", "UnitName", product.UnitID);
            ViewBag.CategoryID = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.SupplierID = new SelectList(_dbConn.Suppliers, "SupplierID", "CompanyName", product.SupplierID);
            return View(product);
        }

        //
        // GET: /Products/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Product product = _dbConn.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Products/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = _dbConn.Products.Find(id);
            _dbConn.Products.Remove(product);
            _dbConn.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {

Gapura/Views/Products/Create.cshtml
@model Gapura.BLL.Models.Product

@{
    ViewBag.Title = "Create Item Product";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-pencil"></i><span class="break"></span>Create Items Product</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Create", "Products", FormMethod.Post, new
        {
            enctype = "multipart/form-data",
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="container">
                    <div class="box span3">
                        <table class="table table-striped">
                            <tr>
                                <td>
                                    <img src="~/UploadFiles/Item/yusenitem.jpg" 
                                        alt="Please select Photo to Attach" width="250" height="450" />
                                    @Html.ValidationMessageFor(m => m.PhotoPath)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="file" id="FileUpload" name="fileUpload" multiple />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="button" id="Upload" value="Upload Photo" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="box span8" style="margin-left: 10px">
                        <div class="box-header">
                            <h4><i class="halflings-icon briefcase"></i><span class="break"></span><b>Item Detail</b></h4>
                            <div class="box-icon">
                            </div>
                        </div>
                        <fieldset>
                            <legend></legend>
                            @Html.HiddenFor(m => m.ProductID)

                            <div class="control-group">
                                @*@Html.Label("ProductCode", "Item Code", new { @class = "control-label" })*@
                                @Html.LabelFor(m => m.ProductCode, new { @class = "control-label" })
                                @Html.EditorFor(m => m.ProductCode)
                                @Html.ValidationMessageFor(m => m.ProductCode)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.CategoryID, new { @class = "control-label" })
                                @Html.DropDownList("CategoryID", String.Empty)
                                @Html.ValidationMessageFor(m => m.CategoryID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.ProductName, new { @class = "control-label" })
                                @Html.TextBox("ProductName", @ViewData["ProductName"], new { @class = "span7 typeahead" })
                                @Html.ValidationMessageFor(m => m.ProductName)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.SupplierID, new { @class = "control-label" })
                                @Html.DropDownList("SupplierID", String.Empty)
                                @Html.ValidationMessageFor(m => m.SupplierID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.QuantityPerUnit, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.QuantityPerUnit, new { @type = "number", @min = "1"})
                                @Html.ValidationMessageFor(m => m.QuantityPerUnit)
                            </div>

                            <div class="control-group">
                                <div class="input-prepend input-append">
                                    @Html.LabelFor(m => m.UnitPrice, new { @class = "control-label" })
                                    <span class="add-on">Rp</span>
                                        @*@Html.TextBoxFor(m => m.UnitPrice, new { @type = "number", @min = "1"})*@
                                        @Html.EditorFor(m => m.UnitPrice, new { @id = "UnitPrice" })
                                    <span class="add-on">.00</span>
                                    @Html.ValidationMessageFor(m => m.UnitPrice)
                                </div>
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.UnitID, new { @class = "control-label" })
                                @Html.DropDownList("UnitID", String.Empty)
                                @Html.ValidationMessageFor(m => m.UnitID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.Specs, new { @class = "control-label" })
                                @*@Html.TextArea("Specs", Model.Specs, new { @rows = "5", @class = "span6 typeahead" })*@
                                @Html.TextAreaFor(m => m.Specs)
                                @Html.ValidationMessageFor(m => m.Specs)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.ReorderLevel, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.ReorderLevel, new { @type = "number", @min = "1"})
                                @Html.ValidationMessageFor(m => m.ReorderLevel)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.Discontinued, new { @class = "control-label" })
                                @Html.EditorFor(m => m.Discontinued)
                                @Html.ValidationMessageFor(m => m.Discontinued)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.FirstInputDate, new { @class = "control-label" })
                                @Html.TextBox("FirstInputDate", @ViewData["FirstInputDate"], new { @readonly = "readonly" })
                                @Html.ValidationMessageFor(m => m.FirstInputDate)
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Reset" class="btn" />
                    <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(m => m.ProductID) })" class="btn btn-danger">Delete</a>
                </div>                    
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery.formatCurrency-1.4.0.js"></script>
<script src="~/Scripts/TextBoxLimit.js"></script>
<script src="~/Scripts/Products/CreateProducts.js"></script>

Gapura/Views/Products/Delete.cshtml
@model Gapura.BLL.Models.Product

@{
    ViewBag.Title = "Delete Item";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Product</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProductName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProductName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Supplier.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Supplier.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category.CategoryName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.CategoryName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.QuantityPerUnit)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.QuantityPerUnit)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitPrice)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitPrice)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitsInStock)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitsInStock)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitsOnOrder)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitsOnOrder)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReorderLevel)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReorderLevel)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Discontinued)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Discontinued)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Gapura/Views/Products/Edit.cshtml
@model Gapura.BLL.Models.Product

@{
    ViewBag.Title = "Edit Item Product";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-edit"></i><span class="break"></span>Edit Items Product</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Edit", "Products", FormMethod.Post, new
        {
            enctype = "multipart/form-data",
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="container">
                    <div class="box span3">
                        <table class="table table-striped">
                            <tr>
                                <td>
                                    <img src="@Url.Content(Model.PhotoPath)" alt="@Url.Content(Model.ProductName)" width="250" height="450" />
                                    @Html.HiddenFor(m => m.PhotoPath)
                                    @Html.ValidationMessageFor(m => m.PhotoPath)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.TextBox("PhotoPath", @ViewData["PhotoPath"], new { @id = "FileUpload", @type ="file" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="button" id="Upload" value="Upload Photo" />
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="box span8" style="margin-left: 10px">
                        <div class="box-header">
                            <h4><i class="halflings-icon tags"></i><span class="break"></span><b>Item Detail</b></h4>
                            <div class="box-icon">
                            </div>
                        </div>
                        <fieldset>
                            <legend></legend>
                            @Html.HiddenFor(m => m.ProductID)

                            <div class="control-group">
                                @*@Html.Label("ProductCode", "Item Code", new { @class = "control-label" })*@
                                @Html.LabelFor(m => m.ProductCode, new { @class = "control-label" })
                                @Html.EditorFor(m => m.ProductCode)
                                @Html.ValidationMessageFor(m => m.ProductCode)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.CategoryID, new { @class = "control-label" })
                                @Html.DropDownList("CategoryID", String.Empty)
                                @Html.ValidationMessageFor(m => m.CategoryID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.ProductName, new { @class = "control-label" })
                                @Html.TextBox("ProductName", @ViewData["ProductName"], new { @class = "span7 typeahead" })
                                @Html.ValidationMessageFor(m => m.ProductName)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.SupplierID, new { @class = "control-label" })
                                @Html.DropDownList("SupplierID", String.Empty)
                                @Html.ValidationMessageFor(m => m.SupplierID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.QuantityPerUnit, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.QuantityPerUnit, new { @type = "number", @min = "1"})
                                @Html.ValidationMessageFor(m => m.QuantityPerUnit)
                            </div>

                            <div class="control-group">
                                <div class="input-prepend input-append">
                                    @Html.LabelFor(m => m.UnitPrice, new { @class = "control-label" })
                                    <span class="add-on">Rp</span>
                                        @*@Html.TextBoxFor(m => m.UnitPrice, new { @type = "number", @min = "1"})*@
                                        @Html.EditorFor(m => m.UnitPrice, new { @id = "UnitPrice" })
                                    <span class="add-on">.00</span>
                                    @Html.ValidationMessageFor(m => m.UnitPrice)
                                </div>
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.UnitID, new { @class = "control-label" })
                                @Html.DropDownList("UnitID", String.Empty)
                                @Html.ValidationMessageFor(m => m.UnitID)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.Specs, new { @class = "control-label" })
                                @*@Html.TextArea("Specs", Model.Specs, new { @rows = "5", @class = "span6 typeahead" })*@
                                @Html.TextAreaFor(m => m.Specs)
                                @Html.ValidationMessageFor(m => m.Specs)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.ReorderLevel, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.ReorderLevel, new { @type = "number", @min = "1"})
                                @Html.ValidationMessageFor(m => m.ReorderLevel)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.Discontinued, new { @class = "control-label" })
                                @Html.EditorFor(m => m.Discontinued)
                                @Html.ValidationMessageFor(m => m.Discontinued)
                            </div>

                            <div class="control-group">
                                @Html.LabelFor(m => m.FirstInputDate, new { @class = "control-label" })
                                @Html.TextBox("FirstInputDate", @ViewData["FirstInputDate"], new { @readonly = "readonly" })
                                @Html.ValidationMessageFor(m => m.FirstInputDate)
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="form-actions">
                    <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                    <input type="reset" value="Reset" class="btn" />
                    <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(m => m.ProductID) })" class="btn btn-danger">Delete</a>
                </div>
                        
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery.formatCurrency-1.4.0.js"></script>
<script src="~/Scripts/TextBoxLimit.js"></script>
<script src="~/Scripts/Products/EditProducts.js"></script>
<script src="~/Scripts/jquery.validate-fixed.js"></script>

Gapura/Views/Products/Index.cshtml
@model IEnumerable<Gapura.BLL.Models.Product>

@{
    ViewBag.Title = "Index Item Products";
}
<script src="~/Scripts/Rpt/Print.js"></script>

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header">
            <h2><i class="icon-table"></i>
                <span class="break"></span>Master Data Items</h2>
            <div class="box-icon">
                @using (Html.BeginForm("PrintListOfItems", "Products"))
                { 
                    <a href="@Url.Action("Create", "Products")">
                        <i class="halflings-icon plus"></i><span class="hidden-tablet"></span>
                        Add New Item
                    </a>
                    <a href="#">
                        <input id="btnPrintListOfItems" onclick="ItemsListPrint()"
                            type="image" src="/Content/img/pdf_button.png" height="30" width="35" />
                    </a>
                }
            </div>
        </div>
        <div class="box-content">
            <div style="width: inherit; margin-left: 0px;">
                <table id="myTable" class="compact stripe hover order-column responsive" @*cellspacing="0"*@ width="100%">
                    <thead>
                        <tr>
                            <th>-</th>
                            <th>Item Code
                            </th>
                            <th>Category
                            </th>
                            <th>Item Name
                            </th>
                            <th>Company
                            </th>
                            <th>Qty Per- Unit
                            </th>
                            <th>Unit Price
                            </th>
                            <th>Unit Name
                            </th>
                            <th>Specs.
                            </th>
                            <th>Re- Order Level
                            </th>
                            <th>End Prod.
                            </th>
                            <th>Input Date
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Products/IndexProducts.js"></script>
}

<style>
    th {
        background-color: #cdcdcd !important;
        border: dotted 1px;
    }

    td {
        border: dotted 1px;
    }
</style>
@Styles.Render("~/Content/dataTables")