Gapura/Controllers/UnitsController.cs
using Gapura.BLL.Models;
using Gapura.Models;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace Gapura.Controllers
{
    [Authorize]
    public class UnitsController : Controller
    {
        private YSIDGAEntitiesConn _dbConn = new YSIDGAEntitiesConn();

        //
        // GET: /Units/

        public ActionResult Index()
        {
            return View(_dbConn.MasterUnits.ToList());
        }

        public JsonResult getUnits()
        {
            List<MasterUnit> units = new List<MasterUnit>();
            using (YSIDGAEntitiesConn dbConn = new YSIDGAEntitiesConn())
            {
                units = dbConn.MasterUnits.OrderBy(u => u.UnitName).ToList();
            }
            return new JsonResult { Data = units, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        //
        // GET: /Units/Details/5

        public ActionResult Details(int id = 0)
        {
            MasterUnit masterUnit = _dbConn.MasterUnits.Find(id);
            if (masterUnit == null)
            {
                return HttpNotFound();
            }
            return View(masterUnit);
        }

        //
        // GET: /Units/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Units/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterUnit masterUnit)
        {
            if (ModelState.IsValid)
            {
                _dbConn.MasterUnits.Add(masterUnit);
                _dbConn.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(masterUnit);
        }

        //
        // GET: /Units/Edit/5

        public ActionResult Edit(int id = 0)
        {
            MasterUnit masterUnit = _dbConn.MasterUnits.Find(id);
            if (masterUnit == null)
            {
                return HttpNotFound();
            }
            return View(masterUnit);
        }

        //
        // POST: /Units/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterUnit masterUnit)
        {
            if (ModelState.IsValid)
            {
                _dbConn.Entry(masterUnit).State = EntityState.Modified;
                _dbConn.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(masterUnit);
        }

        //
        // GET: /Units/Delete/5

        public ActionResult Delete(int id = 0)
        {
            MasterUnit masterUnit = _dbConn.MasterUnits.Find(id);
            if (masterUnit == null)
            {
                return HttpNotFound();
            }
            return View(masterUnit);
        }

        //
        // POST: /Units/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MasterUnit masterUnit = _dbConn.MasterUnits.Find(id);
            _dbConn.MasterUnits.Remove(masterUnit);
            _dbConn.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _dbConn.Dispose();
            base.Dispose(disposing);
        }
    }
}

Gapura/Views/Units/Create.cshtml
@model Gapura.BLL.Models.MasterUnit

@{
    ViewBag.Title = "Create New Unit";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-pencil"></i><span class="break"></span>Create New Unit</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Create", "Units", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    <div class="control-group">
                        @Html.Label("UnitName", "Unit Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.UnitName)
                        @Html.ValidationMessageFor(model => model.UnitName)
                    </div>

                    <div class="control-group">
                        @Html.Label("UnitDesc", "Description", new { @class = "control-label" })

                        @Html.EditorFor(model => model.UnitDesc)
                        @Html.ValidationMessageFor(model => model.UnitDesc)
                    </div>

                    <div class="form-actions">
                        <input type="reset" value="Reset" class="btn" />
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gapura/Views/Units/Delete.cshtml
@model Gapura.BLL.Models.MasterUnit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MasterUnit</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Gapura/Views/Units/Details.cshtml
@model Gapura.BLL.Models.MasterUnit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MasterUnit</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UnitName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gapura/Views/Units/Edit.cshtml
@model Gapura.BLL.Models.MasterUnit

@{
    ViewBag.Title = "Edit Master Units";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-edit"></i><span class="break"></span>Edit Master Unit</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index")"
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Edit", "Units", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    @Html.HiddenFor(model => model.UnitID)

                    <div class="control-group">
                        @Html.Label("UnitName", "Unit Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.UnitName)
                        @Html.ValidationMessageFor(model => model.UnitName)
                    </div>

                    <div class="control-group">
                        @Html.Label("UnitDesc", "Description", new { @class = "control-label" })

                        @Html.EditorFor(model => model.UnitDesc)
                        @Html.ValidationMessageFor(model => model.UnitDesc)
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                        <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(model => model.UnitID) })" class="btn btn-danger">Delete</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gapura/Views/Units/Index.cshtml
@model IEnumerable<Gapura.BLL.Models.MasterUnit>

@{
    ViewBag.Title = "Index of Units";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header">
            <h2><i class="icon-table"></i><span class="break"></span>Set Up New Unit</h2>
            <div class="box-icon">
                <a href="@Url.Action("Create", "Units")">
                    <i class="halflings-icon plus"></i><span class="hidden-tablet"></span>
                    Add New Unit
                </a>
            </div>
        </div>
        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.UnitName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UnitDesc)
                    </th>
                    <th>Action</th>
                </tr>

                @foreach (var item in Model)
                {
                    using (@Html.BeginForm("Delete", "Units", new { item.UnitID }))
                    { @Html.AntiForgeryToken()
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.UnitName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UnitDesc)
                        </td>
                        <td>
                            <a class="btn btn-success"
                                href="@Url.Action("Details", new { id = item.UnitID })">
                                <i class="halflings-icon white zoom-in"></i>
                            </a>
                            <a class="btn btn-info"
                                href="@Url.Action("Edit", new { id = item.UnitID })">
                                <i class="halflings-icon white edit"></i>
                            </a>
                            <a class="btn btn-danger"
                                href="#"
                                onclick="if (confirm('Are you sure want to Delete @item.UnitName ?')) {
                                                $('form').submit();
                                            }
                                            else {
                                                    commentDelete(1); return false
                                            }">
                                <i class="halflings-icon white trash"></i>
                            </a>
                        </td>
                    </tr>
                    }
                }
            </table>
        </div>
    </div>
</div>
<style>
    th {
        background-color: #cdcdcd !important;
        border: dotted 1px;
    }
    td {
        border: dotted 1px;
    }
</style>