Gapura/Controllers/SuppliersController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using Gapura.BLL.Models;
using Gapura.BLL.ViewModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace Gapura.Controllers
{
    [Authorize]
    public class SuppliersController : Controller
    {
        private YSIDGAEntitiesConn _dbConn = new YSIDGAEntitiesConn();

        //
        // GET: /Suppliers/

        public ActionResult Index()
        {
            return View(_dbConn.Suppliers.ToList());
        }

        ///////////////-------------- Load Data by JQuery Fir 26102016 -----------------/////////////
        public ActionResult LoadData()
        {
            //using (YSIDGAEntitiesConn dc = new YSIDGAEntitiesConn())
            {
                _dbConn.Configuration.LazyLoadingEnabled = false;   // if your table is relational, contain foreign key
                #region Various Ways
                //var data = dbConn.Suppliers.OrderBy(s => s.CompanyName).ToList();             //default Way

                //var data = from s in dbConn.Suppliers                                             //Using LinQ
                //           join ca in dbConn.Categories on s.CategoryID equals ca.CategoryID
                //           orderby s.CompanyName
                //           select new { s.SupplierID, s.SupplierCode, ca.CategoryName, s.CompanyName, s.Address, s.City, s.Region, 
                //                        s.ContactName, s.Phone, s.CellPhone, s.Npwp, s.TermOfPayment };
                #endregion

                var data = _dbConn.SPI_Suppliers().ToList();                                 //Using SP
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }
        ///////////////-----------End Load Data by JQuery Fir 26102016 -----------------/////////////

        //
        // GET: /Suppliers/Details/5

        public ActionResult Details(int id = 0)
        {
            Supplier supplier = _dbConn.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // GET: /Suppliers/Create

        public ActionResult Create()
        {
            //ViewBag.CategoryID = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
            //ViewBag.TermID = new SelectList(_dbConn.TermOfPays, "TermID", "TermDays");

            //List<Category> categoryList = _dbConn.Categories.ToList();
            //ViewBag.CategoryList = new SelectList(categoryList, "CategoryID", "CategoryName");

            //List<TermOfPay> termOfPayList = _dbConn.TermOfPays.ToList();
            //ViewBag.TermList = new SelectList(termOfPayList, "TermID", "TermDays");

            SupplierVM supplierVM = new SupplierVM();
            supplierVM.CategoryList = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
            supplierVM.TermOfPayList = new SelectList(_dbConn.TermOfPays, "TermID", "TermDays");

            return View(supplierVM);
        }

        //
        // POST: /Suppliers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SupplierVM supplierVM)
        {
            try {
                if (ModelState.IsValid)
                {
                    Supplier supplier = new Supplier();
                    supplier.SupplierCode = supplierVM.SupplierCode;
                    supplier.CategoryID = supplierVM.CategoryID;
                    supplier.CompanyName = supplierVM.CompanyName;
                    supplier.Address = supplierVM.Address;
                    supplier.City = supplierVM.City;
                    supplier.Region = supplierVM.Region;
                    supplier.ContactName = supplierVM.ContactName;
                    supplier.Phone = supplierVM.Phone;
                    supplier.CellPhone = supplierVM.CellPhone;
                    supplier.Npwp = supplierVM.Npwp;
                    supplier.TermID = supplierVM.TermID;

                    int latestSupplierID = supplier.SupplierID;

                    _dbConn.Suppliers.Add(supplier);
                    _dbConn.SaveChanges();
                    //return RedirectToAction("Index");
                }

                supplierVM.CategoryList = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
                supplierVM.TermOfPayList = new SelectList(_dbConn.TermOfPays, "TermID", "TermDays");

                return View(supplierVM);
            }
            catch (Exception ex) {
                throw ex;
            }
        }

        //
        // GET: /Suppliers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            //var supplier = _dbConn.Suppliers.FirstOrDefault(supplierID => supplierID.SupplierID == id);
            Supplier supplier = _dbConn.Suppliers.Find(id);

            var supplierVM = new SupplierVM();
            supplierVM.SupplierID = id;
            supplierVM.SupplierCode = supplier.SupplierCode;
            supplierVM.CategoryID = supplier.CategoryID;
            supplierVM.CompanyName = supplier.CompanyName;
            supplierVM.Address = supplier.Address;
            supplierVM.City = supplier.City;
            supplierVM.Region = supplier.Region;
            supplierVM.ContactName = supplier.ContactName;
            supplierVM.Phone = supplier.Phone;
            supplierVM.CellPhone = supplier.CellPhone;
            supplierVM.Npwp = supplier.Npwp;
            supplierVM.TermID = supplier.TermID;

            if (supplier == null)
            {
                return HttpNotFound();
            }

            supplierVM.CategoryList = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
            supplierVM.TermOfPayList = new SelectList(_dbConn.TermOfPays, "TermID", "TermDays");

            return View(supplierVM);
        }

        //
        // POST: /Suppliers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SupplierVM supplierVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Supplier supplier = new Supplier();
                    supplier.SupplierID = supplierVM.SupplierID;
                    supplier.SupplierCode = supplierVM.SupplierCode;
                    supplier.CategoryID = supplierVM.CategoryID;
                    supplier.CompanyName = supplierVM.CompanyName;
                    supplier.Address = supplierVM.Address;
                    supplier.City = supplierVM.City;
                    supplier.Region = supplierVM.Region;
                    supplier.ContactName = supplierVM.ContactName;
                    supplier.Phone = supplierVM.Phone;
                    supplier.CellPhone = supplierVM.CellPhone;
                    supplier.Npwp = supplierVM.Npwp;
                    supplier.TermID = supplierVM.TermID;

                    int latestSupplierID = supplier.SupplierID;

                    _dbConn.Entry(supplier).State = EntityState.Modified;
                    _dbConn.SaveChanges();
                    //return RedirectToAction("Index");
                }

                supplierVM.CategoryList = new SelectList(_dbConn.Categories, "CategoryID", "CategoryName");
                supplierVM.TermOfPayList = new SelectList(_dbConn.TermOfPays, "TermID", "TermDays");

                return View(supplierVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //
        // GET: /Suppliers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Supplier supplier = _dbConn.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // POST: /Suppliers/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = _dbConn.Suppliers.Find(id);
            _dbConn.Suppliers.Remove(supplier);
            _dbConn.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _dbConn.Dispose();
            base.Dispose(disposing);
        }

        #region Other ways to Print
        /*
        //Use  Stream  Method -> File will be download and not the open pop up window
        public ActionResult PrintListOfSuppliers()
        {
            using (ReportDocument rptC = new ReportDocument())
            {
                //List data = new List();
                //var data = dbConn.SPR_Suppliers().ToList();
                //rptC.SetDatabaseLogon("firman", "123", "(local)", "YSIDGA");
                //rptC.SetDataSource(data);

                rptC.Load(Path.Combine(Server.MapPath("~/App_Reports"), "SupplierList.rpt"));

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                try{
                    Stream stream = rptC.ExportToStream(ExportFormatType.PortableDocFormat);
                    stream.Seek(0, SeekOrigin.Begin);
                    return File(stream, "application/pdf", "ListofSuppliers.pdf");
                }
                catch (Exception ex){
                    throw;
                }
            }
        }
*/
        #endregion

        public void PrintListOfSuppliers()
        {
            using (ReportDocument rptD = new ReportDocument())
            {
                try {
                    rptD.FileName = Server.MapPath("~/") + "/App_Reports/SupplierList.rpt";
                    //rptC.Load();
                    rptD.SetDatabaseLogon("firman", "123", "(local)", "YSIDGA");

Gapura/Views/Suppliers/Create.cshtml
@model Gapura.BLL.ViewModel.SupplierVM

@{
    ViewBag.Title = "Create Supplier";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-pencil"></i><span class="break"></span>Create Supplier</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index", "Suppliers")" 
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Create", "Suppliers", FormMethod.Post, new
        {
            @class = "form-horizontal",
            @id = "myForm"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    <div class="control-group">
                        @Html.Label("SupplierCode", "Supplier Code", new { @class = "control-label" })

                        @Html.EditorFor(m => m.SupplierCode)
                        @Html.ValidationMessageFor(m => m.SupplierCode)
                    </div>

                    <div class="control-group">
                        @Html.Label("CategoryID", "Category", new { @class = "control-label" })

                        @Html.DropDownListFor(m => m.CategoryID, Model.CategoryList, "--Select--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CategoryID)
                    </div>

                    <div class="control-group">
                        @Html.Label("CompanyName", "Company Name", new { @class = "control-label" })

                        @Html.EditorFor(m => m.CompanyName)
                        @Html.ValidationMessageFor(m => m.CompanyName)
                    </div>

                    <div class="control-group">
                        @Html.Label("Address", "Address", new { @class = "control-label" })

                        @Html.TextAreaFor(m => m.Address)
                        @Html.ValidationMessageFor(m => m.Address)
                    </div>

                    <div class="control-group">
                        @Html.Label("City", "City", new { @class = "control-label" })

                        @Html.EditorFor(m => m.City)
                        @Html.ValidationMessageFor(m => m.City)
                    </div>

                    <div class="control-group">
                        @Html.Label("Region", "Region", new { @class = "control-label" })

                        @Html.EditorFor(m => m.Region)
                        @Html.ValidationMessageFor(m => m.Region)
                    </div>

                    <div class="control-group">
                        @Html.Label("ContactName", "Contact Name", new { @class = "control-label" })

                        @Html.EditorFor(m => m.ContactName)
                        @Html.ValidationMessageFor(m => m.ContactName)
                    </div>

                    <div class="control-group">
                        @Html.Label("Phone", "Phone", new { @class = "control-label", @type = "tel" })

                        @Html.EditorFor(m => m.Phone)
                        @Html.ValidationMessageFor(m => m.Phone)
                    </div>

                    <div class="control-group">
                        @Html.Label("CellPhone", "CellPhone", new { @class = "control-label", @type = "tel" })

                        @Html.EditorFor(m => m.CellPhone)
                        @Html.ValidationMessageFor(m => m.CellPhone)
                    </div>

                    <div class="control-group">
                        @Html.Label("Npwp", "NPWP", new { @class = "control-label" })

                        @Html.EditorFor(m => m.Npwp)
                        @Html.ValidationMessageFor(m => m.Npwp)
                    </div>

                    <div class="control-group">
                        @Html.Label("TermOfPayment", "Term Of Payment", new { @class = "control-label" })

                        @Html.DropDownListFor(m => m.TermID, Model.TermOfPayList, "--Select--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TermID)
                    </div>

                    <div class="form-actions">
                        <input type="button" value="Save" id="btnSave" class="btn btn-success" />
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

<div id="divLoader" style="text-align: center; display: none">
    <img src="../../Content/img/spinner-mini.gif" width="30" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(function () {

        $('#btnSave').click(function () {

            if (!$(myForm).valid()) {
                return false;
            }

            $('#divLoader').show();
            var data = $('#myForm').serialize();

            $.ajax({
                type: 'POST',
                url: '/Suppliers/Create',
                data: data,
                success: function (response) {
                    $('#divLoader').hide();
                    alert('Data Saved !');
                    document.getElementById('myForm').reset();        // native Js
                    //$('#myForm').trigger('reset');  //clear out the form
                }
            })
            .fail(function (xhr, status, errorThrown) {
                alert("Sorry, there was a problem !");
                console.log("Error: " + errorThrown);
                console.log("Status: " + status);
                console.dir(xhr);
            });
            //.always(function (xhr, status) {
            //    alert("The request is complete !");
            //})
        });
    });
</script>

Gapura/Views/Suppliers/Delete.cshtml
@model Gapura.BLL.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Region)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Region)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Gapura/Views/Suppliers/Details.cshtml
@model Gapura.BLL.Models.Supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Region)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Region)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SupplierID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gapura/Views/Suppliers/Edit.cshtml
@model Gapura.BLL.ViewModel.SupplierVM

@{
    ViewBag.Title = "Edit Supplier";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title="">
            <h2><i class="icon-edit"></i><span class="break"></span>Edit Supplier</h2>
            <div class="box-icon">
                <a href="@Url.Action("Index", "Suppliers")" 
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Edit", "Suppliers", FormMethod.Post, new
        {
            @class = "form-horizontal",
            @id = "myForm"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    @Html.HiddenFor(m => m.SupplierID)

                    <div class="control-group">
                        @Html.Label("SupplierCode", "Supplier Code", new { @class = "control-label" })

                        @Html.EditorFor(m => m.SupplierCode)
                        @Html.ValidationMessageFor(m => m.SupplierCode)
                    </div>

                    <div class="control-group">
                        @Html.Label("CategoryID", "Category", new { @class = "control-label" })

                        @Html.DropDownListFor(m => m.CategoryID, Model.CategoryList, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CategoryID)
                    </div>

                    <div class="control-group">
                        @Html.Label("CompanyName", "Company Name", new { @class = "control-label" })

                        @Html.EditorFor(m => m.CompanyName)
                        @Html.ValidationMessageFor(m => m.CompanyName)
                    </div>

                    <div class="control-group">
                        @Html.Label("Address", "Address", new { @class = "control-label" })

                        @Html.TextAreaFor(m => m.Address)
                        @Html.ValidationMessageFor(m => m.Address)
                    </div>

                    <div class="control-group">
                        @Html.Label("City", "City", new { @class = "control-label" })

                        @Html.EditorFor(m => m.City)
                        @Html.ValidationMessageFor(m => m.City)
                    </div>

                    <div class="control-group">
                        @Html.Label("Region", "Region", new { @class = "control-label" })

                        @Html.EditorFor(m => m.Region)
                        @Html.ValidationMessageFor(m => m.Region)
                    </div>

                    <div class="control-group">
                        @Html.Label("ContactName", "Contact Name", new { @class = "control-label" })

                        @Html.EditorFor(m => m.ContactName)
                        @Html.ValidationMessageFor(m => m.ContactName)
                    </div>

                    <div class="control-group">
                        @Html.Label("Phone", "Phone", new { @class = "control-label", @type = "tel" })

                        @Html.EditorFor(m => m.Phone)
                        @Html.ValidationMessageFor(m => m.Phone)
                    </div>

                    <div class="control-group">
                        @Html.Label("CellPhone", "CellPhone", new { @class = "control-label", @type = "tel" })

                        @Html.EditorFor(m => m.CellPhone)
                        @Html.ValidationMessageFor(m => m.CellPhone)
                    </div>

                    <div class="control-group">
                        @Html.Label("Npwp", "NPWP", new { @class = "control-label" })

                        @Html.EditorFor(m => m.Npwp)
                        @Html.ValidationMessageFor(m => m.Npwp)
                    </div>

                    <div class="control-group">
                        @Html.Label("TermDays", "Term Of Payment", new { @class = "control-label" })

                        @Html.DropDownListFor(m => m.TermID, Model.TermOfPayList, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TermID)
                    </div>

                    <div class="form-actions">
                        <input type="button" value="Save" id="btnSave" class="btn btn-success" />
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                        <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(m => m.SupplierID) })" class="btn btn-danger">Delete</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

<div id="divLoader" style="text-align: center; display: none">
    <img src="../../Content/img/spinner-mini.gif" width="30" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(function () {

        $('#btnSave').click(function () {

            if (!$(myForm).valid()) {
                return false;
            }

            $('#divLoader').show();
            var data = $('#myForm').serialize();

            $.ajax({
                type: 'POST',
                url: '/Suppliers/Edit',
                data: data,
                success: function (response) {
                    $('#divLoader').hide();
                    alert('Data Saved !');
                }
            })
            .fail(function (xhr, status, errorThrown) {
                alert("Sorry, there was a problem !");
                console.log("Error: " + errorThrown);
                console.log("Status: " + status);
                console.dir(xhr);
            });
            //.always(function (xhr, status) {
            //    alert("The request is complete !");
            //});
        });
    });
</script>

Gapura/Views/Suppliers/Index.cshtml
@model IEnumerable<Gapura.BLL.Models.Supplier>

@{
    ViewBag.Title = "Supplier List ";
}
<script src="~/Scripts/Rpt/Print.js"></script>

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header">
            <h2><i class="icon-table"></i>
                <span class="break"></span>Master Data Supplier</h2>
            <div class="box-icon">
                @using (Html.BeginForm("PrintListOfSuppliers", "Suppliers"))
                { 
                    <a href="@Url.Action("Create", "Suppliers")">
                        <i class="halflings-icon plus"></i><span class="hidden-tablet"></span>
                        Add New Supplier
                    </a>
                    <a href="#">
                        <input id="btnPrintListOfSuppliers" onclick="SupplierListPrint()"
                            type="image" src="/Content/img/pdf_button.png" height="30" width="35" />
                    </a>
                }
            </div>
        </div>
        <div class="box-content">
            <div style="width: inherit; margin-left: 24px;">
                <table id="myTable" class="compact stripe hover order-column responsive" width="100%">
                    <thead>
                        <tr>
                            <th>-</th>
                            <th>
                                @Html.DisplayNameFor(model => model.SupplierCode)
                            </th>
                            <th>Category Name
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CompanyName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.City)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Region)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ContactName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Phone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CellPhone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Npwp)
                            </th>
                            <th>Terms Day</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/Suppliers/IndexSuppliers.js"></script>
}

<style>
    th {
        background-color: #cdcdcd !important;
        border: dotted 1px;
    }

    td {
        border: dotted 1px;
    }
</style>

@Styles.Render("~/Content/dataTables")